### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [tmehta2442/react-spotify-app#1]
Great job running the app on surge. All the features works as intended. No errors were detected in the code. very nice adding the enter key feature. The app ran ver well. I would suggest learning more javascript array methods which could make our code more precise. Here is a link; 

https://www.w3schools.com/jsref/jsref_obj_array.asp

**Comment by tmehta2442** [comment]
Totally agree... In the back of my mind I was thinking there had to be a 'cleaner' way of iterating over the arrays. Thanks for setting it up for me.
